# Generated by Django 4.1.2 on 2023-03-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='firts_name',
            new_name='firsts_name',
        ),
    ]
